# Generated by Django 3.2.7 on 2021-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=122, null=True)),
                ('youremail', models.CharField(max_length=122, null=True)),
                ('yoursubject', models.TextField(null=True)),
                ('yourmessage', models.TextField(null=True)),
            ],
        ),
    ]
